import React, { FC } from 'react';
import Head from "next/head";
import NewsContainer from "../containers/NewsContainer";
import { dehydrate, QueryClient } from "react-query";
import { QueryDefaultValue } from "../types/QueryDefaultValue";
import { getFeed } from "../utils/fetchApi";

const Page: FC = () => {
  return (
    <div className={"container"}>
      <Head>
        <title>Involta Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NewsContainer />
    </div>
  );
};

export async function getServerSideProps(ctx: any) {
  const { source,  search, page} = ctx.query
  const queryClient = new QueryClient()
  await queryClient.prefetchQuery(["getAllNews", {
      sort: "date",
      page: page ? page : 1,
      limit: 3,
      source: source ? source : QueryDefaultValue.source,
      search: search ? search : QueryDefaultValue.search
    }],
    getFeed
  )

  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    },
  }
}

export default Page;