import Head from 'next/head'
import NewsContainer from "../containers/NewsContainer";
import  { fetchApi } from "./api/mosFetcher";
import { MosNewsType } from "../types/mosNewsType";
import { FC, useEffect } from "react";

interface Props {
  data: MosNewsType[];
}

const Home: FC<Props> = ({data}) => {

  useEffect(() => console.log(data), [data])


  return (
    <div className={"container"}>
      <Head>
        <title>Involta Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<h1>{data[0].title}</h1>*/}
      {/*{data && data.map((t, index) => (*/}
      {/*  <h1 key={index}>{t.title}</h1>*/}
      {/*))}*/}

      <NewsContainer />
    </div>
  )
}
1
export async function getServerSideProps() {
  const data = await fetchApi<MosNewsType[]>()
  console.log(data);

  return { props: {data}  }
}

export default Home
