import Head from 'next/head'
import { FC } from "react";

const Home: FC = () => {

  return (
    <div className={"container"}>
      <Head>
        <title>Involta Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Загрузка...</h1>
    </div>
  )
}

export default Home
